### PR TITLE
ODEProblem and CoevolveSynced

### PR DESCRIPTION
**Pull request by gzagatti**
I started an attempt to map the PDMP problem to an ODEProblem to use the aggregators available in JumpProcesses.

Given that some of the jumps depend on a continuous variable, there are two options for aggregators either `Direct` or `CoevolveSynced` (SciML/JumpProcesses.jl#315). 

I have tried to run the test with the `Direct` aggregator but I ran into the following issue. I tried different ODE solvers (`Tsit5`, `AutoTsit5(Rosenbrock23())` and `lsoda`).

```
Error: Tried to add a tstop that is behind the current time. This is strictly forbidden.
```

It's likely that there is a bug in the implementation. So it's probably worth double-checking it.

To use `CoevolveSynced` we need to define the upper bound rates and the interval for which they are valid given `t` and `u` in [here](https://github.com/gzagatti/SynapseElife/blob/e4f8a5570cde191434d6d9e5317fb1e9462999c1/src/SynapseModelODEProblem.jl#L58).

### CODE REVIEW

**Comment by rveltz** [comment]
Hi,

Thank you a lot for your work!

This rep will be the main rep for the code of the publication. I am waiting for the editor to approve it. Then I need to "tag" this as the code for the paper, so people can replicate the findings.

Perhaps we should put your work in a branch?

**Comment by gzagatti** [comment]
Yes, please feel free to put the work on a separate branch. I was not sure about the best way to share it.

**Comment by gzagatti** [comment]
My latest push refactors the source code to accommodate the ODE problem with only minor changes to the API. 

I have made sure that the test in `simplerun.jl` works for the PDMP and the ODE problems. I found that `CoevolveSynced` is way faster than `Direct` which is quite promissing. To reproduce the tests, you will want to use [this branch of JumpProcesses.jl](https://github.com/SciML/JumpProcesses.jl/pull/315).

However, the solver is facing instability issues. I have tried using different solvers to address the issue with no avail which suggests that there might be a bug in my implementation of the ODE Problem. It would be great if you could double check that the model is correct before we start playing with the solver. There are so many equations and small details that I am afraid I could have modified something unintentionally.

Second, in order to get `CoevolveSynced` running we need to define the local bounds of the problem. Given time `t` and state `u` can we derive local bounds for the variable jumps (i.e. jumps 56 to 75)? Figure 17 of the [latest draft of your paper](https://www.biorxiv.org/content/10.1101/2021.03.30.437703v3.full.pdf) plots bounds for VGCC rates and temperature factors. So, I took the bounds from there. I am not sure if it's correct. Ideally, we could parameterize them in the source code. It's just a matter of modifying [lines 435-460 of the model](https://github.com/gzagatti/SynapseElife/blob/coevolve/src/ModelODE.jl#L435).

I hope that we can get this working. I am looking forward to benchmark the performance of PDMP and CoevolveSynced on a practical application.

**Comment by gzagatti** [comment]
I fixed the ODE problem. There were quite a few bugs here and there (e.g. indices, breaks in equations without proper line continuation, assigning the wrong variable, etc.). 

Now, the test in `simplerun.jl` successfully runs for the ODE problem with `Direct` aggregator. Here is a preliminary comparsion for the variables `Vsp` and `N_ampa`.

image

image

On my machine, I got the following using the `AutoTsit5(Rosenbrock23())`.

- PDMP problem:
    - `SimGluOFF`: `0.885362 seconds (41.81 k allocations: 14.840 MiB)`
    - `evolveSynapse`: `1.636618 seconds (92.95 k allocations: 40.565 MiB)`

- ODE problem with `Direct` aggregator:
    - `SimGluOFF`: `13.179566 seconds (21.13 M allocations: 6.638 GiB, 4.11% gc time)`
    - `evolveSynapse`: `23.427810 seconds (38.10 M allocations: 11.966 GiB, 4.18% gc time)`

What about `CoevolveSynced`? I found that I can run a single simulation test (a single call to `solve`run in `6.775784 seconds (17.72 M allocations: 3.913 GiB, 7.17% gc time)`). However, I cannot run `evolveSynapse`. The reason is as following. In the ODE problem `u` holds both the continuous `u[1:34]` and discrete variables `u[35end]`:. Therefore, the vector contains `Float64` elements. When the solver steps, it tends to introduce small errors to `u`. When `u[36] == 0`, we might end up with `u[36] = -ε` even when `du[36] = 0`. With a negative value we end computing a negative rate which should not be allowed in any jump process and is strictly enforced in `CoevolveSynced`. Therefore, the call to `evolveSynapse` fails.

`PDMP` treats continuous and discrete variables separately and does not pass the discrete variables to the continuos solver. Ideally, `JumpProcesses.jl` should do something similar.

Apart from that,  when using `CoevolveSynced` I have not optimized the rates upper boundaries which could result in a large number of rejections and the larger running time. However, I haven't tested that.

What next? 

1. In the Discourse thread you mentioned that you have an analytical expression of the jump process that can attest the error. Can we use this code to test whether the ODE Problem is correct using the `Direct` aggregator.

2. Define better upper bounds and rate interval to improve the performance of `CoevolveSynced`.

3. Open an issue in `JumpProcesses.jl` to discuss the handling of continuous and discrete variables on ODE problems.

**Comment by gzagatti** [comment]
I figured out that the real reason why `CoevolveSynced` was failing on `evolveSynapse` was because there was a bug in `buildRXDependencyGraph`. With that out of the way, all the three different algorithms output a similar results as you can see below. The code to generate the plots can be found [here](https://github.com/gzagatti/SynapseElife/blob/coevolve/test/simplerun.jl).

Vsp

N_ampa

It would be a good idea to check whether `CoevolveSynced` and `Direct` are producing the correct results.

On my machine, I got the following times using the `AutoTsit5(Rosenbrock23())` solver:

- PDMP problem:
    - `SimGluOFF`: `0.989999 seconds (47.45 k allocations: 17.472 MiB)`
    - `evolveSynapse`: `1.636325 seconds (94.82 k allocations: 42.205 MiB)`

- ODE problem with `CoevolveSynced` aggregator:
    - `SimGluOFF`: `9.136452 seconds (8.45 M allocations: 4.790 GiB, 6.52% gc time)`
    - `evolveSynapse`: `18.473426 seconds (17.42 M allocations: 9.861 GiB, 6.74% gc time, 0.05% compilation time)`

- ODE problem with `Direct` aggregator:
    - `SimGluOFF`: `10.653863 seconds (15.21 M allocations: 4.779 GiB, 3.89% gc time)`
    - `evolveSynapse`: `21.126133 seconds (31.30 M allocations: 9.743 GiB, 4.12% gc time`

It might look that `CoevolveSynced` did not improve much from `Direct`. However, the results above are misleading. In fact, `CoevolveSynced` can perform much better.

When coupling a jump problem with a continuous one, `CoevolveSynced` is the only aggregator that can still queue discrete callbacks in the continuous solver. However, if we put the discrete variables together with the continuous ones in the vector `u`, they are also optimized by the solver which leads to a bigger ODE which is more expensive to solve. In addition to that, numerical errors can easily creep in to variables that should be discrete. 

As an alternative, I came up with a different formulation of the problem which is available [in branch `coevolve-ii`](https://github.com/gzagatti/SynapseElife/blob/coevolve-ii/src/ModelODE.jl). In this case, all of the discrete variables are kept together in parameter vector `p`. When a jump occurs we update `p` instead of `u`. The continuous solver then only see the continuous variables. 

With this in place we cut the time of `CoevolveSynced` by almost 4 as you can see below (again using the `AutoTsit5(Rosenbrock23())` solver):

- PDMP problem:
    - `SimGluOFF`: `0.929155 seconds (45.01 k allocations: 16.687 MiB)`
    - `evolveSynapse`: ` 1.643075 seconds (95.30 k allocations: 43.286 MiB, 0.73% gc time)`

- ODE problem with `CoevolveSynced` aggregator:
    - `SimGluOFF`: `2.386971 seconds (3.93 M allocations: 1.962 GiB, 15.12% gc time)`
    - `evolveSynapse`: `4.984636 seconds (7.88 M allocations: 4.021 GiB, 14.49% gc time)`

The resulting plots are also comparable:

Vsp-coevolve

N_ampa-coevolve

**What next?**

1. We should compute the errors of the new implementations to ensure that they are correct?

2. We need to define better upper bounds and rate interval to improve the performance of `CoevolveSynced`. A better grasp of the model will help a lot in here.

3. Look for obvious performance improvements [in this branch](https://github.com/gzagatti/SynapseElife/blob/coevolve/src/ModelODE.jl) or  [in branch `coevolve-ii`](https://github.com/gzagatti/SynapseElife/blob/coevolve-ii/src/ModelODE.jl). There are likely a lot of low hanging fruits.

4. What's the ideal design pattern for coupling the jump and ODE problems of this benchmark?

**Comment by rveltz** [comment]
Great work!! Really.


 I would tend to think that you allocate à lot. Perhaps this is one thing to investigate

**Comment by gzagatti** [comment]
Thanks for your encouragement!

I have done some additional work on the allocation as you suggested. I managed to bring it down by quite a lot.

There was an obvious mistake when indexing the variable `u` it makes a copy. This was by far the biggest allocator.

```julia
	Vsp, Vdend, Vsoma, λ, ImbufCa, Ca, Dye, CaM0, CaM2C, CaM2N, CaM4, mCaN,
	CaN4, mKCaM, KCaM0, KCaM2N, KCaM2C, KCaM4, PCaM0, PCaM2C, PCaM2N, PCaM4, P, P2,
	LTD, LTP, act_D, act_P, m, h, n, SK, λ_age, λ_aux = u[1:34]
```

Apart from that, fine-tuning the saving locations cut down a good amount of memory.

With all that in place, we cut down running time from 3x PDMP to 2x (again using the `AutoTsit5(Rosenbrock23())` solver on the [`coevolve-ii` branch](https://github.com/gzagatti/SynapseElife/blob/coevolve-ii/src/ModelODE.jl)). Note that the running times reported below are slower compared to my previous post because I am now running everything on the server's lab:

- PDMP problem:
    - `SimGluOFF`: `1.448469 seconds (47.74 k allocations: 16.743 MiB)`
    - `evolveSynapse`: `2.652094 seconds (101.80 k allocations: 43.076 MiB)`

- ODE problem with `CoevolveSynced` aggregator:
    - `SimGluOFF`: `2.653456 seconds (133.63 k allocations: 39.176 MiB)`
    - `evolveSynapse`: `5.279871 seconds (296.49 k allocations: 86.470 MiB)`
   
I did some further investigation to determine the reason behind the difference in memory allocation. For both `CoevolveSynced` and `PDMP`, most of the memory is allocated during `differentiation/compute_jacobian_ad.jl` . My main conclusion is that the difference between the algorithms is driven by the high rejection rate of the jumps in `CoevolveSynced` which hovers around 70%. This translates into about 2x to 3x more function evaluations and Jacobians created when solving the ODE problem. Therefore, I don't think we can increase the performance of `CoevolveSynced` on par with `PDMP` without better bounds.

<details><summary>For future reference, unfold to see a comparison of the plots and the logs.</summary>

image

image

- PDMP problem:

```julia
julia> pdmpresult = @time evolveSynapse(
               xc0,
               xd0,
               p_synapse,
               events_sorted_times,    # external events
               is_pre_or_post_event,   # pre or post?
               bap_by_epsp,
               [true],
               nu,
               pdmpalgos,
               pdmpagg;
               save_positions = pdmpsave_positions,
       );
┌ Info: Integrator
│   integrator.stats =
│    DiffEqBase.Stats
│    Number of function 1 evaluations:                  106916
│    Number of function 2 evaluations:                  0
│    Number of W matrix evaluations:                    23578
│    Number of linear solves:                           70734
│    Number of Jacobians created:                       23578
│    Number of nonlinear solver iterations:             0
│    Number of nonlinear solver convergence failures:   0
│    Number of rootfind condition calls:                24423
│    Number of accepted steps:                          24423
│    Number of rejected steps:                          374
└    Maximum eigenvalue recorded:                       377
┌ Info: Integrator
│   integrator.stats =
│    DiffEqBase.Stats
│    Number of function 1 evaluations:                  77362
│    Number of function 2 evaluations:                  0
│    Number of W matrix evaluations:                    0
│    Number of linear solves:                           0
│    Number of Jacobians created:                       0
│    Number of nonlinear solver iterations:             0
│    Number of nonlinear solver convergence failures:   0
│    Number of rootfind condition calls:                11587
│    Number of accepted steps:                          11587
│    Number of rejected steps:                          6
└    Maximum eigenvalue recorded:                       1
┌ Info: Integrator
│   integrator.stats =
│    DiffEqBase.Stats
│    Number of function 1 evaluations:                  224254
│    Number of function 2 evaluations:                  0
│    Number of W matrix evaluations:                    28708
│    Number of linear solves:                           86124
│    Number of Jacobians created:                       28708
│    Number of nonlinear solver iterations:             0
│    Number of nonlinear solver convergence failures:   0
│    Number of rootfind condition calls:                43527
│    Number of accepted steps:                          43527
│    Number of rejected steps:                          1889
└    Maximum eigenvalue recorded:                       376
  1.448469 seconds (47.74 k allocations: 16.743 MiB)
┌ Info: last bit
│   length(res.time) = 8494
│   tt[end] = 1000.0
└   p_synapse.t_end = 1000.0
  2.652094 seconds (101.80 k allocations: 43.076 MiB)
```

- ODE problem with `CoevolveSynced` aggregator:

```julia
julia> coresult = @time evolveSynapse(
               xc0,
               xd0,
               p_synapse,
               events_sorted_times,    # external events
               is_pre_or_post_event,   # pre or post?
               bap_by_epsp,
               [true],
               nu,
               jalgos,
               coagg;
               save_positions = jsave_positions,
               saveat = jsaveat,
               save_everystep = false,
       );
┌ Info: Integrator
│   sol.xcsol.stats =
│    DiffEqBase.Stats
│    Number of function 1 evaluations:                  350908
│    Number of function 2 evaluations:                  0
│    Number of W matrix evaluations:                    78164
│    Number of linear solves:                           234492
│    Number of Jacobians created:                       78164
│    Number of nonlinear solver iterations:             0
│    Number of nonlinear solver convergence failures:   0
│    Number of rootfind condition calls:                168540
│    Number of accepted steps:                          84270
│    Number of rejected steps:                          195
└    Maximum eigenvalue recorded:                       3876
┌ Info: Rejection rate
└   rejection_rate = 0.6891985538726493
┌ Info: Integrator
│   sol.xcsol.stats =
│    DiffEqBase.Stats
│    Number of function 1 evaluations:                  69183
│    Number of function 2 evaluations:                  0
│    Number of W matrix evaluations:                    0
│    Number of linear solves:                           0
│    Number of Jacobians created:                       0
│    Number of nonlinear solver iterations:             0
│    Number of nonlinear solver convergence failures:   0
│    Number of rootfind condition calls:                20756
│    Number of accepted steps:                          10378
│    Number of rejected steps:                          11
└    Maximum eigenvalue recorded:                       2142
┌ Info: Rejection rate
└   rejection_rate = 0.6677018633540373
┌ Info: Integrator
│   sol.xcsol.stats =
│    DiffEqBase.Stats
│    Number of function 1 evaluations:                  466782
│    Number of function 2 evaluations:                  0
│    Number of W matrix evaluations:                    82279
│    Number of linear solves:                           246837
│    Number of Jacobians created:                       82279
│    Number of nonlinear solver iterations:             0
│    Number of nonlinear solver convergence failures:   0
│    Number of rootfind condition calls:                207190
│    Number of accepted steps:                          103595
│    Number of rejected steps:                          1114
└    Maximum eigenvalue recorded:                       4161
┌ Info: Rejection rate
└   rejection_rate = 0.6994097344064
  2.653456 seconds (133.63 k allocations: 39.176 MiB)
┌ Info: last bit
│   length(res.xcsol.t) = 9981
│   tt[end] = 1000.0
└   p_synapse.t_end = 1000.0
  5.279871 seconds (296.49 k allocations: 86.470 MiB)
```
</details>

**What next?**

I have enough to benchmark `PDMP` and `CoevolveSynced`. I will try to include these results and discussion in the `Coevolve` paper.

Unless, there is a suggestion for better rejection bounds I won't try to squeeze additional performance. 

Apart from that, it would be great if you could share the code to compute the errors just to ensure that the `Coevolve` implementation is correct.

Any further suggestions to improve the design pattern or to improve performance would be more than welcome.

**Comment by rveltz** [comment]
> . For both CoevolveSynced and PDMP, most of the memory is allocated during differentiation/compute_jacobian_ad.jl

Do you know if MTK could improve it?

> Any further suggestions to improve the design pattern or to improve performance would be more than welcome.

In the rejection, you only need the sum of the rates, you dont need the vector of rates. You can parametrize this in PDMP and this can boost performances.

Also, in your preprint, you did not discuss the precision-speed for different time-steppers. On the website (docs) of PDMP, this is shown how it can severely impact the precision even for "robust" time steppers

**Comment by gzagatti** [comment]
Thanks for your feedback again!

As you might have noticed, I have made a PR to `SciMLBenchmarks.jl` with a benchmark of the synapse model SciML/SciMLBenchmarks.jl#597.

Feel free to close this PR and we can move our discussion to thread of that PR since it is all benchmark related.

> Do you know if MTK could improve it?

I am not very familiar with MTK (I am assuming you mean ModellingToolKit). Maybe something to learn next :)

> In the rejection, you only need the sum of the rates, you dont need the vector of rates. You can parametrize this in PDMP and this can boost performances.

That's a good idea! If I had more time, that is something I would consider benchmarking.

In [`PiecewiseDeterministicMarkovProcesses.jl/src/rejectiondiffeq.jl`](https://github.com/rveltz/PiecewiseDeterministicMarkovProcesses.jl/blob/master/src/rejectiondiffeq.jl), the user needs to supply the total upper bound rate. If this is significantly less expensive than computing the sum of all the bounds, then this will improve the efficiency of the simulator because it is `O(1)`. Alternatively, if we need to re-compute all bounds this is `O(n)`. This trade-off will be problem dependent.

Second, you still need to compute the vector of rates once the jump is accepted which takes `O(n)`. Moreover, in the worst case scenario, you need to loop through this vector when selecting the jump (`pfsample(...)`), which is `O(n)`.

With `Coevolve`, we keep all the rates separate and only update those that change. If the candidate is rejected, we only need to re-compute the upper bound of the rejected candidate `O(1)` and update the priority queue which takes `O(0.5 log(n+1))` in the worse case. 

If the candidate is accepted and the dependency graph is sparse, this result in `O(k+1)` updates where `k` is the number of dependencies. Next, we need to push the candidate times to the priority queue which takes `O(0.5 log(n+1))`.

Does it make sense?

> Also, in your preprint, you did not discuss the precision-speed for different time-steppers. On the website (docs) of PDMP, this is shown how it can severely impact the precision even for "robust" time steppers.

Are you referring to [this section](https://rveltz.github.io/PiecewiseDeterministicMarkovProcesses.jl/dev/solver/#Simulation-methods-1)? If so, I've started drafting a benchmark for it in [here](https://github.com/gzagatti/SciMLBenchmarks.jl/blob/switching-dynamics/benchmarks/Jumps/SwitchingDynamics.jmd).

I will keep your feedback in mind for the next revision of the paper which I am preparing at the moment.

**Pull request closed without merging**
